[package]
name = "mapping"
version = "0.1.0"
authors = ["sjmackenzie <setori88@gmail.com>"]

[profile.release]
opt-level = 3
debug = false

[lib]
name = "mapping"
crate-type = ["dylib"]

[dependencies]
fst = "*"
