[package]
name = "shells_lain_commands_dirname"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "shells_lain_commands_dirname"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
