[package]
name = "net_socket_server"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "net_socket_server"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
nanomsg = "0.5.0"
