
[package]
name = "shells_lain_prompt"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "shells_lain_prompt"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
toml = "*"
libc = "*"
copperline = "*"
