[package]
name = "serialize_json_decode_extractKVfromVec"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "serialize_json_decode_extractKVfromVec"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
serde = "*"
serde_macros = "*"
serde_json = "*"
