
[package]
name = "shells_lain_parse"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "shells_lain_parse"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
nom = "*"
