[package]
name = "net_socket_client"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "net_socket_client"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
