[package]
name = "print_file_with_feedback"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "print_file_with_feedback"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
