[package]
name = "web_server"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "web_server"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
iron = "*"
mount = "*"
staticfile = "*"
