[package]
name = "net_websocket_server"
version = "0.1.0"
authors = ["Stewart Mackenzie <setori88@gmail.com>"]

[lib]
name = "net_websocket_server"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
ws = "*"
