[package]
name = "maths_number_add"
version = "0.1.0"
authors = ["Denis Michiels <dmichiels@gmail.com>"]

[lib]
name = "maths_number_add"
crate-type = ["dylib"]

[dependencies]
capnp = "*"
rustfbp = "*"
