[package]
name = "ui_conrod_window"
version = "0.1.0"
authors = ["test <test@test.com>"]

[lib]
name = "ui_conrod_window"
crate-type = ["dylib"]

[dependencies]
rustfbp = "*"
capnp = "*"
piston_window = "*"
pistoncore-sdl2_window = "*"

